name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            SHA224PASS
            PROXYIP
        env:
          SHA224PASS: ${{ secrets.SHA224PASS }}
          PROXYIP: ${{ secrets.PROXYIP }}
